-- r_job_category 增加字段
alter table r_job_category
    add spanish_name varchar(128) null comment '西班牙语',
    add japanese_name varchar(128) null comment '日语';
-- 更新对应的字段值
UPDATE `r_job_category`
SET `japanese_name` = CASE `id`
                          WHEN 1 THEN '会計と金融サービス'
                          WHEN 2 THEN '広告とマーケティング'
                          WHEN 3 THEN '農業と栽培業'
                          WHEN 4 THEN '自動車と輸送'
                          WHEN 5 THEN '美容とパーソナルケア'
                          WHEN 6 THEN '建設と請負業'
                          WHEN 7 THEN 'コンサルティングと専門サービス'
                          WHEN 8 THEN '教育とトレーニング'
                          WHEN 9 THEN 'エネルギーと公益事業'
                          WHEN 10 THEN 'エンターテイメントとメディア'
                          WHEN 11 THEN '食品と飲料'
                          WHEN 12 THEN 'ヘルスケア'
                          WHEN 13 THEN 'ホテルと観光業'
                          WHEN 14 THEN '情報技術'
                          WHEN 15 THEN '法律と法務サービス'
                          WHEN 16 THEN '製造業と工業'
                          WHEN 17 THEN '非営利団体と慈善事業'
                          WHEN 18 THEN '不動産と物件管理'
                          WHEN 19 THEN '小売業と電子商取引'
                          WHEN 20 THEN 'スポーツとレジャー'
                          WHEN 21 THEN '電気通信'
                          WHEN 22 THEN '旅行と観光'
                          WHEN 23 THEN '卸売業と流通'
                          WHEN 24 THEN '環境保護とグリーン産業'
                          WHEN 25 THEN 'ファッションと衣料品'
                          WHEN 26 THEN 'インテリアとデザイン'
                          WHEN 27 THEN '音楽と芸術'
                          WHEN 28 THEN '写真とビデオ撮影'
                          WHEN 29 THEN '社会サービスと公益提唱'
                          WHEN 30 THEN 'テクノロジーとソフトウェア'
                          WHEN 31 THEN 'ウェブ開発とデザイン'
                          WHEN 32 THEN '保育と幼児教育'
                          WHEN 33 THEN 'フィットネスとヘルス'
                          WHEN 34 THEN 'グラフィックデザインとクリエイティブサービス'
                          WHEN 35 THEN '保険とリスクマネジメント'
                          WHEN 36 THEN '法律と弁護士補助サービス'
                          WHEN 37 THEN '製造と生産'
                          WHEN 38 THEN 'キャリア開発とトレーニング'
                          WHEN 39 THEN '再生可能エネルギーとクリーンテクノロジー'
                          WHEN 40 THEN 'セキュリティと監視'
                          WHEN 41 THEN '旅行とホテルサービス'
                          WHEN 42 THEN 'イベント企画と管理'
                          WHEN 43 THEN '環境サービスと持続可能な開発'
                          WHEN 44 THEN 'ペットサービスと獣医療'
                          WHEN 45 THEN '航空宇宙と国防'
                          WHEN 46 THEN 'バイオテクノロジーと製薬'
                          WHEN 47 THEN '政府と公共管理'
                          WHEN 48 THEN '研究開発'
                          WHEN 49 THEN '輸送と物流'
                          WHEN 50 THEN '結婚式とイベントサービス'
                          WHEN 51 THEN '人工知能とオートメーション'
                          WHEN 52 THEN 'コンテンツ作成'
                          WHEN 53 THEN '人事'
                          WHEN 54 THEN 'フリーランスと請負契約業務'
                          WHEN 55 THEN 'エンジニアリング'
                          WHEN 56 THEN 'ビジネスと金融'
                          WHEN 57 THEN 'マーケティングと販売'
                          WHEN 58 THEN '小売業とカスタマーサービス'
                          WHEN 59 THEN '科学研究'
                          WHEN 60 THEN 'その他' ELSE `japanese_name`
    END,
    `spanish_name` = CASE `id`
                         WHEN 1 THEN 'Contabilidad y servicios financieros'
                         WHEN 2 THEN 'Publicidad y marketing'
                         WHEN 3 THEN 'Agricultura y cultivo'
                         WHEN 4 THEN 'Automoción y transporte'
                         WHEN 5 THEN 'Belleza y cuidado personal'
                         WHEN 6 THEN 'Construcción y contratación'
                         WHEN 7 THEN 'Consultoría y servicios profesionales'
                         WHEN 8 THEN 'Educación y formación'
                         WHEN 9 THEN 'Energía y servicios públicos'
                         WHEN 10 THEN 'Entretenimiento y medios'
                         WHEN 11 THEN 'Alimentos y bebidas'
                         WHEN 12 THEN 'Salud médica'
                         WHEN 13 THEN 'Hostelería y turismo'
                         WHEN 14 THEN 'Tecnologías de la información'
                         WHEN 15 THEN 'Derecho y servicios legales'
                         WHEN 16 THEN 'Manufactura e industria'
                         WHEN 17 THEN 'Sin ánimo de lucro y caridad'
                         WHEN 18 THEN 'Inmobiliaria y propiedad'
                         WHEN 19 THEN 'Venta minorista y comercio electrónico'
                         WHEN 20 THEN 'Deportes y ocio'
                         WHEN 21 THEN 'Telecomunicaciones'
                         WHEN 22 THEN 'Viajes y turismo'
                         WHEN 23 THEN 'Mayorista y distribución'
                         WHEN 24 THEN 'Protección ambiental e industria verde'
                         WHEN 25 THEN 'Moda y vestimenta'
                         WHEN 26 THEN 'Hogar y diseño de interiores'
                         WHEN 27 THEN 'Música y arte'
                         WHEN 28 THEN 'Fotografía y videografía'
                         WHEN 29 THEN 'Servicios sociales y promoción pública'
                         WHEN 30 THEN 'Tecnología y software'
                         WHEN 31 THEN 'Desarrollo y diseño web'
                         WHEN 32 THEN 'Cuidado infantil y educación temprana'
                         WHEN 33 THEN 'Fitness y salud'
                         WHEN 34 THEN 'Diseño gráfico y servicios creativos'
                         WHEN 35 THEN 'Seguros y gestión de riesgos'
                         WHEN 36 THEN 'Derecho y servicios de asistencia legal'
                         WHEN 37 THEN 'Fabricación y producción'
                         WHEN 38 THEN 'Desarrollo profesional y formación'
                         WHEN 39 THEN 'Energía renovable y tecnologías limpias'
                         WHEN 40 THEN 'Seguridad y vigilancia'
                         WHEN 41 THEN 'Servicios de viaje y hostelería'
                         WHEN 42 THEN 'Organización y gestión de eventos'
                         WHEN 43 THEN 'Servicios ambientales y desarrollo sostenible'
                         WHEN 44 THEN 'Servicios para mascotas y cuidado veterinario'
                         WHEN 45 THEN 'Aeroespacio y defensa'
                         WHEN 46 THEN 'Biotecnología y farmacia'
                         WHEN 47 THEN 'Gobierno y administración pública'
                         WHEN 48 THEN 'Investigación y desarrollo'
                         WHEN 49 THEN 'Transporte y logística'
                         WHEN 50 THEN 'Servicios de bodas y eventos'
                         WHEN 51 THEN 'Automatización de inteligencia artificial'
                         WHEN 52 THEN 'Creación de contenido'
                         WHEN 53 THEN 'Recursos humanos'
                         WHEN 54 THEN 'Trabajo independiente y por contrato'
                         WHEN 55 THEN 'Ingeniería'
                         WHEN 56 THEN 'Negocios y finanzas'
                         WHEN 57 THEN 'Marketing y ventas'
                         WHEN 58 THEN 'Venta minorista y atención al cliente'
                         WHEN 59 THEN 'Investigación científica'
                         WHEN 60 THEN 'Otros' ELSE `spanish_name`
        END
WHERE `id` BETWEEN 1 AND 60;